server:
  port: 8090

spring:
  application:
    name: "cars"
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5442/cars-db
    username: cars
    password: cars
    hikari:
      auto-commit: false
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: create-drop
  servlet:
    multipart:
      max-file-size: 5MB

#Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true